from PyQt5 import QtCore, QtGui, QtWidgets


class PomodoroUI(object):
    def setupUi(self, pomodoro_window):
        pomodoro_window.setObjectName("pomodoro_window")
        pomodoro_window.resize(329, 297)
        self.centralwidget = QtWidgets.QWidget(pomodoro_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.home)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.create_pomodoro_btn = QtWidgets.QPushButton(self.home)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.create_pomodoro_btn.setFont(font)
        self.create_pomodoro_btn.setObjectName("create_pomodoro_btn")
        self.verticalLayout_5.addWidget(self.create_pomodoro_btn)
        self.stacked_widget.addWidget(self.home)
        self.categories = QtWidgets.QWidget()
        self.categories.setObjectName("categories")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.categories)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.previous_window_btn1 = QtWidgets.QPushButton(self.categories)
        self.previous_window_btn1.setObjectName("previous_window_btn1")
        self.horizontalLayout_7.addWidget(self.previous_window_btn1)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.label = QtWidgets.QLabel(self.categories)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.categories)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.cat_layout = QtWidgets.QVBoxLayout()
        self.cat_layout.setObjectName("cat_layout")
        self.cat_btn1 = QtWidgets.QPushButton(self.categories)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cat_btn1.setFont(font)
        self.cat_btn1.setObjectName("cat_btn1")
        self.cat_layout.addWidget(self.cat_btn1)
        self.verticalLayout_2.addLayout(self.cat_layout)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.categories)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.new_category_text = QtWidgets.QLineEdit(self.categories)
        self.new_category_text.setObjectName("new_category_text")
        self.horizontalLayout.addWidget(self.new_category_text)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.add_new_cat_btn = QtWidgets.QPushButton(self.categories)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_new_cat_btn.setFont(font)
        self.add_new_cat_btn.setObjectName("add_new_cat_btn")
        self.verticalLayout_2.addWidget(self.add_new_cat_btn)
        self.stacked_widget.addWidget(self.categories)
        self.projects = QtWidgets.QWidget()
        self.projects.setObjectName("projects")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.projects)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.previous_window_btn2 = QtWidgets.QPushButton(self.projects)
        self.previous_window_btn2.setObjectName("previous_window_btn2")
        self.horizontalLayout_6.addWidget(self.previous_window_btn2)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.projects)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.projects)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.proj_layout = QtWidgets.QVBoxLayout()
        self.proj_layout.setObjectName("proj_layout")
        self.proj_btn1 = QtWidgets.QPushButton(self.projects)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.proj_btn1.setFont(font)
        self.proj_btn1.setObjectName("proj_btn1")
        self.proj_layout.addWidget(self.proj_btn1)
        self.verticalLayout.addLayout(self.proj_layout)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.projects)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.new_project_text = QtWidgets.QLineEdit(self.projects)
        self.new_project_text.setObjectName("new_project_text")
        self.horizontalLayout_2.addWidget(self.new_project_text)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.add_proj_btn = QtWidgets.QPushButton(self.projects)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_proj_btn.setFont(font)
        self.add_proj_btn.setObjectName("add_proj_btn")
        self.verticalLayout.addWidget(self.add_proj_btn)
        self.stacked_widget.addWidget(self.projects)
        self.timer = QtWidgets.QWidget()
        self.timer.setObjectName("timer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.timer)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.previous_window_btn3 = QtWidgets.QPushButton(self.timer)
        self.previous_window_btn3.setObjectName("previous_window_btn3")
        self.horizontalLayout_8.addWidget(self.previous_window_btn3)
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.current_proj = QtWidgets.QLabel(self.timer)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.current_proj.setFont(font)
        self.current_proj.setText("")
        self.current_proj.setAlignment(QtCore.Qt.AlignCenter)
        self.current_proj.setObjectName("current_proj")
        self.verticalLayout_4.addWidget(self.current_proj)
        self.working_resting_label = QtWidgets.QLabel(self.timer)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.working_resting_label.setFont(font)
        self.working_resting_label.setText("")
        self.working_resting_label.setAlignment(QtCore.Qt.AlignCenter)
        self.working_resting_label.setObjectName("working_resting_label")
        self.verticalLayout_4.addWidget(self.working_resting_label)
        self.timer_label = QtWidgets.QLabel(self.timer)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.timer_label.setFont(font)
        self.timer_label.setText("")
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.verticalLayout_4.addWidget(self.timer_label)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.start_pomodoro_btn = QtWidgets.QPushButton(self.timer)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.start_pomodoro_btn.setFont(font)
        self.start_pomodoro_btn.setObjectName("start_pomodoro_btn")
        self.verticalLayout_6.addWidget(self.start_pomodoro_btn)
        self.add_recall_btn = QtWidgets.QPushButton(self.timer)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.add_recall_btn.setFont(font)
        self.add_recall_btn.setObjectName("add_recall_btn")
        self.verticalLayout_6.addWidget(self.add_recall_btn)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.end_proj_btn = QtWidgets.QPushButton(self.timer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.end_proj_btn.setFont(font)
        self.end_proj_btn.setObjectName("end_proj_btn")
        self.horizontalLayout_3.addWidget(self.end_proj_btn)
        self.cancel_proj_btn = QtWidgets.QPushButton(self.timer)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_proj_btn.setFont(font)
        self.cancel_proj_btn.setObjectName("cancel_proj_btn")
        self.horizontalLayout_3.addWidget(self.cancel_proj_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.pomodoro_added_label = QtWidgets.QLabel(self.timer)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pomodoro_added_label.setFont(font)
        self.pomodoro_added_label.setText("")
        self.pomodoro_added_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pomodoro_added_label.setObjectName("pomodoro_added_label")
        self.verticalLayout_6.addWidget(self.pomodoro_added_label)
        self.stacked_widget.addWidget(self.timer)
        self.verticalLayout_7.addWidget(self.stacked_widget)
        pomodoro_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(pomodoro_window)
        self.stacked_widget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(pomodoro_window)

    def retranslateUi(self, pomodoro_window):
        _translate = QtCore.QCoreApplication.translate
        pomodoro_window.setWindowTitle(_translate("pomodoro_window", "Pomodoro"))
        self.create_pomodoro_btn.setText(
            _translate("pomodoro_window", "Create a pomodoro")
        )
        self.previous_window_btn1.setText(_translate("pomodoro_window", "Previous"))
        self.label.setText(_translate("pomodoro_window", "Categories"))
        self.label_2.setText(_translate("pomodoro_window", "Select a category: "))
        self.cat_btn1.setText(_translate("pomodoro_window", "Category 1"))
        self.label_3.setText(_translate("pomodoro_window", "Add a new category: "))
        self.add_new_cat_btn.setText(_translate("pomodoro_window", "Add category"))
        self.previous_window_btn2.setText(_translate("pomodoro_window", "Previous"))
        self.label_4.setText(_translate("pomodoro_window", "Projects"))
        self.label_5.setText(_translate("pomodoro_window", "Select a project: "))
        self.proj_btn1.setText(_translate("pomodoro_window", "Project 1"))
        self.label_6.setText(_translate("pomodoro_window", "Add a new project:  "))
        self.add_proj_btn.setText(_translate("pomodoro_window", "Add project"))
        self.previous_window_btn3.setText(_translate("pomodoro_window", "Previous"))
        self.start_pomodoro_btn.setText(_translate("pomodoro_window", "Start"))
        self.add_recall_btn.setText(_translate("pomodoro_window", "Add a recall"))
        self.end_proj_btn.setText(_translate("pomodoro_window", "End project"))
        self.cancel_proj_btn.setText(_translate("pomodoro_window", "Cancel project"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    pomodoro_window = QtWidgets.QMainWindow()
    ui = PomodoroUI()
    ui.setupUi(pomodoro_window)
    pomodoro_window.show()
    sys.exit(app.exec_())
